- name: Download Files From Novogene
  hosts: localhost
  vars:
    ## Populated from inventory: batchid, send_to_email, test_mode, 
    ##test_mode: false
    test_mode: true
    send_email: true
    send_notification: true
  vars_files:
  - vars/fixed.yaml     ## fixed variables that shouldn't need to change
  - vars/dynamic.yaml   ## dynamically generated variables from fixed
  - vars/messages.yaml  ## messages related to signals
  become: no
  pre_tasks:
  - name: Install dependencies
    when: not test_mode
    include_tasks: playbooks/install-dependencies.yaml

  - name: Prime the working dir
    become: no
    file:
       path: '{{ working_dir }}'
       state: directory
       recurse: yes
 
  tasks:
  ## Queue must always be the first signal
  - name: Queue ansible job
    include_tasks: playbooks/queue-ansible.yaml

  - name: Initialise tasks
    include_tasks: playbooks/send-signals.yaml
        
  - name: Setup test batch data
    when: test_mode
    include_tasks: playbooks/test-batch.yaml

  - name: Get JSON manifest
    when: not test_mode
    include_tasks: playbooks/run-puppeteer.yaml

  - name: Process the archives
    include_tasks: playbooks/process-archives.yaml

  - name: Process the FASTQs
    include_tasks: playbooks/process-fastqs.yaml

  - name: Upload FASTQs to Galaxy
    include_tasks: playbooks/upload-to-galaxy.yaml

  - name: Archive files locally
    include_tasks: playbooks/archive-files.yaml

  - name: Update samplesheet
    include_tasks: playbooks/update-samplesheet.yaml

  - include_tasks: playbooks/send-signals.yaml
    vars: {signal: finish}

  post_tasks:
  - name: Remove ansible lock file
    file:
      path: '{{ ansible_lock_file }}'
      state: absent

  # - name: Remove test batch data
  #   when: test_mode
  #   include_tasks: playbooks/test-batch.yaml
