- name: Download Files From Novogene
  hosts: localhost
  vars:
    ## Populated from inventory: batchid, send_to_email, test_mode, 
    test_mode: true
    send_update_email: True
  vars_files:
  - vars/fixed.yaml     ## fixed variables that shouldn't need to change
  - vars/dynamic.yaml   ## dynamically generated variables from fixed
  become: no
  ##- include: playbooks/generate-testdata.yaml
  pre_tasks:
  - name: Install dependencies
    include_tasks: playbooks/install-dependencies.yaml

  - name: Prime the working dir
    become: no
    ansible.builtin.file:
       path: '{{ working_dir }}'
       state: directory
       recurse: yes
       
  - name: Setup test batch data
    when: test_mode
    include_tasks: playbooks/test-batch.yaml

  tasks:
  - name: Run queued email
    include_tasks: playbooks/run-emails.yaml
    vars: {param: queued}

  - name: Queue ansible job
    include_tasks: playbooks/queue-ansible.yaml

  - name: Send processing email
    include_tasks: playbooks/run-emails.yaml
    vars: {param: processing}

  - name: Get JSON manifest
    include_tasks: playbooks/run-puppeteer.yaml

  - name: Process the archives
    include_tasks: playbooks/process-archives.yaml

  - name: Process the FASTQs
    include_tasks: playbooks/process-fastqs.yaml

  - name: Upload FASTQs to Galaxy
    include_tasks: playbooks/upload-to-galaxy.yaml

  - name: Archive files locally
    include_tasks: playbooks/archive-files.yaml

  - name: Update samplesheet
    include_tasks: playbooks/update-samplesheet.yaml

  - name: Send final email
    include_tasks: playbooks/run-emails.yaml
    vars: {param: final}

  post_tasks:
  - name: Remove ansible lock file
    file:
      path: '{{ ansible_lock_file }}'
      state: absent
