- name: Send Notification
  when: send_notification
  tags: notify
  vars:
    signal: "queue"
    prefix: "{{ lookup('pipe', 'date \"+%H:%M:%S\"') }} | "
    ## Dynamic
    message: '{{ prefix }}{{ sigdict[signal] }}'
    last_id: "{{ lookup('file', notif_id) if signal != 'queue' else '' }}"
    last_message: "{{ lookup('file', notif_msg) if signal != 'queue' else '' }}"
  shell:
    cmd: |
      {% if signal == "queue" %}
      echo '{{ message }}' > '{{ notif_msg }}';
      bash {{ script_phosh }} notify send "{{ notify_subject }}" "{{ message }}" > {{ notif_id }}
      {% else %}
      echo '{{ message }}' >> '{{ notif_msg }}';
         {% if replace_notif %}
      bash {{ script_phosh }} notify update {{ last_id }} "{{ notify_subject }}" "{{ message }}" "{{ last_message }}"
         {% else %}
      bash {{ script_phosh }} notify send "{{ notify_subject }}" "{{ message }}" "{{ last_message }}" >> {{ notif_id }}
         {% endif %}
      {% endif %}
