- name: Save data to archive
  block:
  - name: Mount novogene archives rw
    shell: sudo mount -o 'remount,rw' '{{ novogene_mount }}' || sudo mount -o 'rw' '{{ novogene_mount }}'

  - name: Move Unpacked Files to Archive
    synchronize:
       archive: true
       recursive: true
       src: '{{ working_dir }}/{{ upload_dir }}/'
       dest: '{{ novogene_mount }}/{{ novogene_subdir }}/{{ batchid }}'

  - name: Move supporting files to Archive
    vars:
       from_locn : "{{ working_dir }}/{{ upload_dir }}"    ## ensure NO trailing slash
       dest_root : "{{ novogene_mount }}/{{ novogene_subdir }}"
       dest_batt : "{{ dest_root }}/{{ batchid }}"
    shell:
      chdir: '{{ working_dir }}'
      cmd: |
        mv -i -v {{ batchid }}.* {{ dest_root }}/;
        cp -v files_given.md5s {{ dest_batt }}.MD5;
        cp -v sample_ids.txt {{ dest_batt }}.IDs;
        mv -i -v {{ working_dir }}/{{ unpacked_dir }}/*Report*.zip {{ dest_batt }}.report.zip;

  - name: Unmount novogene archives
    shell: |
      sudo sync
      sudo umount '{{ novogene_mount }}'
