- name: All processing signals
  vars:
    email_subject: "Novogene Batch Download: {{ batchid }}"
  block:
  - name: Signal queued
    when: param == "queue"
    block:
    - name: Set state to queued
      shell:
        cmd: |
          bash {{ email_script }} novogene_set_state {{ batchid }} queued
    
    - name: Send Email Queued
      when: send_update_email
      shell:
        chdir: '{{ email_folder }}'
        cmd: |
          gmi send {{ send_to_email }} << EOF
          To: {{ send_to_email }}
          Subject: {{ email_subject }}
          Content-Type: text/html; charset="UTF-8"
          -----------------
    
          <html><body><pre>
          <i>(Bleep, bloop.)</i>
          This is an automatic email to let you know that the
          Novogene Sequence Retrieval Pipeline is running!
  
          status: <b>{{ batchid }}</b> is <i>waiting</i> in the queue.
          </pre></body></html>
    
          EOF
    
    - name: Get ID of last email and set it for future chains
      when: send_update_email
      shell:
        chdir: '{{ email_folder }}'
        cmd: |
          notmuch show --format=json --sort=newest-first --body=false \
                  tag:sent subject:{{ email_subject }} \
                  | jq .'[0][][0].id' | xargs echo | tee {{ email_chain }}
  
  
  - name: Signal processing
    when: param == "process"
    block:
    - name: Set state to processing
      shell:
        cmd: |
          bash {{ email_script }} novogene_set_state {{ batchid }} processing
    
    - name: Send Email Processing
      when: send_update_email
      vars:
        last_email_sent: "{{ lookup('file', email_chain) }}"
      shell:
        chdir: '{{ email_folder }}'
        cmd: |
          gmi send {{ send_to_email }} << EOF
          To: {{ send_to_email }}
          References: <{{ last_email_sent }}>
          In-Reply-To: <{{ last_email_sent }}>
          Subject: {{ email_subject }}
          Content-Type: text/html; charset="UTF-8"
          -----------------
    
          <html><body><pre>
          status: <b>{{ batchid }}</b> is being <i>processed</i>.
          </pre></body></html>
    
          EOF
  
  - name: Signal download
    when: param == "download"
    block:
    - name: Send Email Downloading
      when: send_update_email
      vars:
        last_email_sent: "{{ lookup('file', email_chain) }}"
      shell:
        chdir: '{{ email_folder }}'
        cmd: |
          gmi send {{ send_to_email }} << EOF
          To: {{ send_to_email }}
          References: <{{ last_email_sent }}>
          In-Reply-To: <{{ last_email_sent }}>
          Subject: {{ email_subject }}
          Content-Type: text/html; charset="UTF-8"
          -----------------
  
          <html><body><pre>
          status: <b>{{ batchid }}</b> is being <i>downloaded</i>.
          </pre></body></html>
  
          EOF
          
  - name: Signal galaxy
    when: param == "galaxy"
    block:
    - name: Send Email Galaxy
      vars:
        last_email_sent: "{{ lookup('file', email_chain) }}"
      shell:
        chdir: '{{ email_folder }}'
        cmd: |
          gmi send {{ send_to_email }} << EOF
          To: {{ send_to_email }}
          References: <{{ last_email_sent }}>
          In-Reply-To: <{{ last_email_sent }}>
          Subject: {{ email_subject }}
          Content-Type: text/html; charset="UTF-8"
          -----------------
  
          <html><body><pre>
          status: <b>{{ batchid }}</b> is being <i>uploaded to Galaxy</i>.
          </pre></body></html>
  
          EOF


  - name: Signal archiving
    when: param == "archive"
    block:
    - name: Send Email Archiving
      vars:
        last_email_sent: "{{ lookup('file', email_chain) }}"
      shell:
        chdir: '{{ email_folder }}'
        cmd: |
          gmi send {{ send_to_email }} << EOF
          To: {{ send_to_email }}
          References: <{{ last_email_sent }}>
          In-Reply-To: <{{ last_email_sent }}>
          Subject: {{ email_subject }}
          Content-Type: text/html; charset="UTF-8"
          -----------------
  
          <html><body><pre>
          status: <b>{{ batchid }}</b> is being <i>archived</i> to disk.
          </pre></body></html>
  
          EOF


  
  - name: Signal final
    when: param == "finish"
    block:
    - name: Set state to finished
      shell:
        cmd: |
          bash {{ email_script }} novogene_set_state {{ batchid }} finished
  
    - name: Send Email final
      when: send_update_email
      vars:
        last_email_sent: "{{ lookup('file', email_chain) }}"
      shell:
        chdir: '{{ email_folder }}'
        cmd: |
          gmi send {{ send_to_email }} << EOF
          References: <{{ last_email_sent }}>
          In-Reply-To: <{{ last_email_sent }}>
          To: {{ send_to_email }}
          Subject: Re: {{ email_subject }}
          Content-Type: text/html; charset="UTF-8"
          -----------------
  
          <html><body><pre>
          Novogene batch <b>{{ batchid }}</b> is <i>finished.</i>
          <small>(downloaded, checked, uploaded to Galaxy, and locally archived).</small>\
          <hr/>\
          <i>Sample IDs</i>     : {{ sample_ids_inline.msg }}
          <i>Archived To</i>    : {{ novogene_mount }}/{{ novogene_subdir }}/{{ batchid }}
          <i>Galaxy History</i> : {{ batchid }}
          <i>Samplesheet</i>    : {{ remote_tsv | basename }} (updated)
          <hr/>
          Please note:
  
             The Galaxy history <b>{{ batchid }}</b>
             should <u>not</u> be used for processing.
  
             Please <u>copy the data into another history</u>
             and process it there.
  
          Happy analyzing!
          </pre></body></html>
  
          EOF
            
  
  