- name: Set Email states
  when: signal in emaildict
  shell: bash {{ script_email }} novogene_set_state {{ batchid }} {{ emaildict[signal] }}

- name: Set Signalling states
  when: signal in sigdict
  block:
  - include_tasks: playbooks/bits/notify.yaml
  - include_tasks: playbooks/bits/email.yaml
