- name: Don't run puppeteer, install test data
  block:
  - name: Generate or retrieve batch
    include_tasks: playbooks/generate-testdata.yaml

  - name: Install test files
    copy:
      src : '{{ testdata_cache }}/{{ batchid }}.{{ item.src }}'
      dest: '{{ working_dir }}/{{ item.dest }}'
    loop:
     - { src: 'tar'  , dest: '{{ batchid }}.tar' }
     - { src: 'MD5'  , dest: 'MD5.txt'    }
     - { src: 'json' , dest: 'batch.json' }
     - { src: 'email', dest: 'email.txt'  }

    ## TODO: install only if not already present
  - name: Install fake email to notmuch
    block:
    - name: Check if email already exists
      shell:
         cmd: notmuch search subject:{{ batchid }} tag:new
      register: email_exists

    - name: Install email if not exists
      shell:
        chdir: '{{ working_dir }}'
        cmd: cat email.txt | notmuch insert --folder mail -tags +unread
      when: email_exists.stdout | trim != ""

  - name: Set the email state
    shell:
      chdir: '{{ working_dir }}'
      cmd: notmuch tag +unread subject:{{ batchid }} tag:new
      ##cmd: cat email.txt | notmuch insert --folder mail -tags +unread
