- name: Don't run puppeteer, install test data
  block:
  - name: Generate or retrieve batch
    include_tasks: playbooks/generate-testdata.yaml
    ## inherits: batchid, testdata_cache
 
  - name: Install test archive
    copy:
      src : '{{ testdata_cache }}/{{ batchid }}.tar'
      dest: '{{ working_dir }}/{{ batchid }}.tar'
  - name: Install test MD5
    copy:
      src : '{{ testdata_cache }}/{{ batchid }}.MD5'
      dest: '{{ working_dir }}/MD5.txt'
  - name: Install test JSON
    copy:
      src : '{{ testdata_cache }}/{{ batchid }}.json'
      dest: '{{ working_dir }}/batch.json'
  - name: Install test email
    copy:
      src : '{{ testdata_cache }}/{{ batchid }}.email'
      dest: '{{ working_dir }}/email.txt'
      
  - name: Install fake email to notmuch
    shell:
      chdir: '{{ working_dir }}'
      cmd: cat email.txt | notmuch insert --folder mail -tags +unread
