- name: Don't run puppeteer, install test data
  block:
  - name: Generate or retrieve batch
    include_tasks: playbooks/generate-testdata.yaml

  - name: Install test files
    copy:
      src : '{{ testdata_cache }}/{{ batchid }}.{{ item.src }}'
      dest: '{{ working_dir }}/{{ item.dest }}'
    loop:
     - { src: 'tar'  , dest: '{{ batchid }}.tar' }
     - { src: 'MD5'  , dest: 'MD5.txt'    }
     - { src: 'json' , dest: 'batch.json' }
     - { src: 'email', dest: 'email.txt'  }


  - name: Install fake email to notmuch
    shell:
      chdir: '{{ working_dir }}'
      cmd: cat email.txt | notmuch insert --folder mail -tags +unread
