- name: Log data in spreadsheet
  block:
  - include_tasks: playbooks/send-signals.yaml
    vars: {signal: logged}
    
  - name: Read sample IDs again
    tags: email
    shell:
       cmd: cat '{{ working_dir }}/sample_ids.txt'
    register: sample_ids

  - name: Inline sample_ids
    tags: email
    debug:
      msg: "{{ sample_ids.stdout | split('\n') | join(', ') }}"
    register: sample_ids_inline

  - name: Append new record to local sheet
    blockinfile:
      path: '{{ local_sheet }}'
      backup: true
      marker: ": {mark} {{ batchid }} ansible"
      insertafter: EOF
      block: |
       ** DONE Upload Data:
       CLOSED: [{{ org_timestamp }}]
       :PROPERTIES:
       :BATCHNO:  {{ batchid }}
       :FILEDIR:  {{ novogene_subdir }}/{{ batchid }}
       :IDS:      {{ sample_ids_inline.msg }}
       :GALAXY:   {{ batchid }}
       :END:

  - name: Convert sheet to tabular
    shell: |
       emacs -nw -Q --batch '{{ local_sheet }}' --eval \
       '(progn (setq filename_export "{{ local_tsv }}") (goto-char 0)(org-next-block 1)(let ((org-confirm-babel-evaluate nil)) (org-ctrl-c-ctrl-c)))'

  - name: Mount lab data rw
    shell: sudo mount -o 'remount,rw' '{{ labdata_mount }}' || sudo mount -o 'rw' '{{ labdata_mount }}'

  - name: Copy over local sheet to remote
    become_user: root
    copy:
      src: '{{ local_sheet }}'
      dest: '{{ remote_sheet }}'

  - name: Copy over local tsv to remote
    become_user: root
    copy:
      src: '{{ local_tsv }}'
      dest: '{{ remote_tsv }}'

  - name: Unmount lab data
    shell: |
      sudo sync
      sudo umount '{{ labdata_mount }}'
